### ISSUE TITLE
Build Linux Version?

### ISSUE THREAD

**Issue by benrusza** [OpenATBP/OpenATBPClient#4]
I try to run via wine but not work

I appreciate

**Comment by CakeLancelot** [comment]
Unfortunately not possible as Unity never released a build of Web Player for Linux. If you're having issues running under Wine check [this page](https://github.com/OpenFusionProject/OpenFusion/wiki/Running-the-game-client-on-Linux). It is for a different Web Player game (FusionFall) but most still applies to ATBP.
